# Generated by Django 4.0 on 2022-12-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='in_list',
            field=models.BooleanField(default=False),
        ),
    ]
