# Generated by Django 4.0 on 2022-12-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_movie_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.TextField(default=''),
        ),
    ]
